[project]
directory = "."
sources = ["rtl/xlnxdemo_oracle.v", "rtl/trace_tb0.v", "rtl/trace_tb1.v"]
toplevel = "xlnxdemo"

[[bugs]]
name = "s1b"
original = "rtl/xlnxdemo_oracle.v"
buggy = "rtl/xlnxdemo_bug_s1b.v"

[[bugs]]
name = "s1r"
original = "rtl/xlnxdemo_oracle.v"
buggy = "rtl/xlnxdemo_bug_s1r.v"

# This is the original testbench from CirFix
[[testbenches]]
name = "tb0_s1b"
sources = ["sources_bug_s1b.txt"]
output = "output_s1_axi_lite.txt"
oracle = "oracle_tb0.txt"
timeout = 7.0

[[testbenches]]
name = "tb1_s1r"
sources = ["sources_bug_s1r.txt"]
output = "output_s1_axi_lite.txt"
oracle = "oracle_tb1.txt"
timeout = 7.0
